name: PROD - Deployment to GooglePlay
on:
  push:
    tags:
      - PROD*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Firebase
        uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: ${{secrets.FIREBASE_TOKEN}}

      - name: set up JDK 11
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ADD LOCAL PROPERTIES
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: ADD GOOGLE SERVICE
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build AAB
        id: buildAAB
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: signAAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to Play Store
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.jhk.cicd_aos
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          whatsNewDirectory: distribution/whatsnew
